version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - '80:80'
    depends_on:
      - mysql